# Generated by Django 5.0.4 on 2024-05-24 08:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StripeCustomerModel',
            fields=[
                ('id', models.CharField(editable=False, max_length=255, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.JSONField(blank=True, null=True, verbose_name='Address')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='Description')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Name')),
                ('phone', models.CharField(blank=True, max_length=255, null=True, verbose_name='Phone')),
                ('shipping', models.JSONField(blank=True, null=True, verbose_name='Shipping')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Metadata')),
            ],
            options={
                'verbose_name': 'Stripe Customer',
                'verbose_name_plural': 'Stripe Customers',
            },
        ),
        migrations.CreateModel(
            name='StripeInvoiceModel',
            fields=[
                ('id', models.CharField(editable=False, max_length=255, primary_key=True, serialize=False)),
                ('auto_advance', models.BooleanField(default=False, verbose_name='Auto Advance')),
                ('currency', models.CharField(max_length=3, verbose_name='Currency')),
                ('current_period_end', models.DateTimeField(verbose_name='Current Period End')),
                ('current_period_start', models.DateTimeField(verbose_name='Current Period Start')),
                ('customer', models.CharField(max_length=255, verbose_name='Customer ID')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('lines', models.JSONField(verbose_name='Lines')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Metadata')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('open', 'Open'), ('paid', 'Paid'), ('uncollectible', 'Uncollectible'), ('void', 'Void')], max_length=50, verbose_name='Status')),
                ('hosted_invoice_url', models.URLField(blank=True, null=True, verbose_name='Hosted Invoice URL')),
                ('subscription', models.CharField(blank=True, max_length=255, null=True, verbose_name='Subscription ID')),
            ],
            options={
                'verbose_name': 'Stripe Invoice',
                'verbose_name_plural': 'Stripe Invoices',
                'ordering': ['-current_period_end'],
            },
        ),
        migrations.CreateModel(
            name='StripePlanModel',
            fields=[
                ('id', models.CharField(editable=False, max_length=255, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('amount', models.IntegerField(blank=True, null=True, verbose_name='Amount')),
                ('amount_decimal', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Amount Decimal')),
                ('currency', models.CharField(choices=[('usd', 'US Dollar'), ('eur', 'Euro')], max_length=3, verbose_name='Currency')),
                ('interval', models.CharField(choices=[('day', 'Day'), ('week', 'Week'), ('month', 'Month'), ('year', 'Year')], max_length=10, verbose_name='Interval')),
                ('interval_count', models.IntegerField(default=1, verbose_name='Interval Count')),
                ('billing_scheme', models.CharField(choices=[('per_unit', 'Per Unit'), ('tiered', 'Tiered')], max_length=20, verbose_name='Billing Scheme')),
                ('created', models.DateTimeField(verbose_name='Created')),
                ('livemode', models.BooleanField(default=False, verbose_name='Live Mode')),
                ('metadata', models.JSONField(blank=True, null=True, verbose_name='Metadata')),
                ('nickname', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nickname')),
                ('product', models.CharField(blank=True, max_length=255, null=True, verbose_name='Product ID')),
                ('tiers_mode', models.CharField(blank=True, max_length=20, null=True, verbose_name='Tiers Mode')),
                ('transform_usage', models.JSONField(blank=True, null=True, verbose_name='Transform Usage')),
                ('trial_period_days', models.IntegerField(blank=True, null=True, verbose_name='Trial Period Days')),
                ('usage_type', models.CharField(choices=[('metered', 'Metered'), ('licensed', 'Licensed')], default='licensed', max_length=10, verbose_name='Usage Type')),
            ],
            options={
                'verbose_name': 'Stripe Plan',
                'verbose_name_plural': 'Stripe Plans',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='StripeProductModel',
            fields=[
                ('id', models.CharField(editable=False, max_length=255, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('default_price', models.CharField(blank=True, max_length=255, null=True, verbose_name='Default Price')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Metadata')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('object', models.CharField(max_length=50, verbose_name='Object Type')),
                ('created', models.DateTimeField(verbose_name='Created')),
                ('images', models.JSONField(blank=True, default=list, verbose_name='Images')),
                ('livemode', models.BooleanField(default=False, verbose_name='Live Mode')),
                ('marketing_features', models.JSONField(blank=True, default=list, verbose_name='Marketing Features')),
                ('package_dimensions', models.JSONField(blank=True, null=True, verbose_name='Package Dimensions')),
                ('shippable', models.BooleanField(blank=True, null=True, verbose_name='Shippable')),
                ('statement_descriptor', models.CharField(blank=True, max_length=255, null=True, verbose_name='Statement Descriptor')),
                ('tax_code', models.CharField(blank=True, max_length=255, null=True, verbose_name='Tax Code')),
                ('unit_label', models.CharField(blank=True, max_length=50, null=True, verbose_name='Unit Label')),
                ('updated', models.DateTimeField(verbose_name='Updated')),
                ('url', models.URLField(blank=True, null=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Stripe Product',
                'verbose_name_plural': 'Stripe Products',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='StripeSetupIntentModel',
            fields=[
                ('id', models.CharField(editable=False, max_length=255, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_secret', models.CharField(max_length=255, verbose_name='Client Secret')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('last_setup_error', models.JSONField(blank=True, null=True, verbose_name='Last Setup Error')),
                ('next_action', models.JSONField(blank=True, null=True, verbose_name='Next Action')),
                ('status', models.CharField(choices=[('requires_payment_method', 'Requires Payment Method'), ('requires_confirmation', 'Requires Confirmation'), ('requires_action', 'Requires Action'), ('processing', 'Processing'), ('canceled', 'Canceled'), ('succeeded', 'Succeeded')], max_length=50, verbose_name='Status')),
                ('usage', models.CharField(blank=True, max_length=50, null=True, verbose_name='Usage')),
                ('cancellation_reason', models.CharField(blank=True, max_length=255, null=True, verbose_name='Cancellation Reason')),
                ('created', models.DateTimeField(verbose_name='Created')),
                ('livemode', models.BooleanField(default=False, verbose_name='Live Mode')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Metadata')),
            ],
            options={
                'verbose_name': 'Stripe Setup Intent',
                'verbose_name_plural': 'Stripe Setup Intents',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='StripeSubscriptionModel',
            fields=[
                ('id', models.CharField(editable=False, max_length=255, primary_key=True, serialize=False, verbose_name='ID')),
                ('cancel_at_period_end', models.BooleanField(default=False, verbose_name='Cancel at Period End')),
                ('currency', models.CharField(max_length=3, verbose_name='Currency')),
                ('current_period_end', models.DateTimeField(verbose_name='Current Period End')),
                ('current_period_start', models.DateTimeField(verbose_name='Current Period Start')),
                ('customer', models.CharField(max_length=255, verbose_name='Customer ID')),
                ('default_payment_method', models.CharField(blank=True, max_length=255, null=True, verbose_name='Default Payment Method')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('items', models.JSONField(verbose_name='Items')),
                ('latest_invoice', models.CharField(blank=True, max_length=255, null=True, verbose_name='Latest Invoice')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Metadata')),
                ('pending_setup_intent', models.CharField(blank=True, max_length=255, null=True, verbose_name='Pending Setup Intent')),
                ('pending_update', models.JSONField(blank=True, null=True, verbose_name='Pending Update')),
                ('status', models.CharField(choices=[('incomplete', 'Incomplete'), ('incomplete_expired', 'Incomplete Expired'), ('trialing', 'Trialing'), ('active', 'Active'), ('past_due', 'Past Due'), ('canceled', 'Canceled'), ('unpaid', 'Unpaid'), ('paused', 'Paused')], max_length=50, verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Stripe Subscription',
                'verbose_name_plural': 'Stripe Subscriptions',
                'ordering': ['-current_period_end'],
            },
        ),
        migrations.CreateModel(
            name='FirebaseUserInformations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email_verified', models.BooleanField()),
                ('sign_in_provider', models.CharField(max_length=255)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Firebase User Informations',
                'verbose_name_plural': 'Firebase User Informations',
                'unique_together': {('user', 'sign_in_provider')},
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.CharField(choices=[('STRIPE', 'Stripe'), ('LEMON', 'LemonSqueezy')], max_length=10)),
                ('subscription_id', models.CharField(max_length=255)),
                ('plan_id', models.CharField(max_length=255)),
                ('customer_id', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Subscription',
                'verbose_name_plural': 'Subscriptions',
                'unique_together': {('user', 'plan_id')},
            },
        ),
    ]
