# Generated by Django 5.0.4 on 2024-05-24 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drf_easily_saas', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subscription',
        ),
    ]
